/**
 * fonts.js
 *
 * Complete list of fonts to probe for fingerprinting.
 * Organized by category for readability.
 *
 * HOW DETECTION WORKS:
 * We measure text width with each font + a baseline fallback.
 * If width differs from baseline → font is installed on the system.
 *
 * Coverage:
 * - Windows system fonts
 * - macOS system fonts
 * - Linux system fonts
 * - Adobe / Creative Cloud fonts
 * - Google Fonts (common ones)
 * - Microsoft Office fonts
 * - Developer / coding fonts
 */

export const FONT_LIST = [
  // ==================
  // Windows System Fonts
  // ==================
  "Arial",
  "Arial Black",
  "Arial Narrow",
  "Arial Rounded MT Bold",
  "Bahnschrift",
  "Calibri",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Ebrima",
  "Franklin Gothic Medium",
  "Gabriola",
  "Gadugi",
  "Georgia",
  "HoloLens MDL2 Assets",
  "Impact",
  "Ink Free",
  "Javanese Text",
  "Leelawadee UI",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Malgun Gothic",
  "Marlett",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft YaHei",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "Mongolian Baiti",
  "MS Gothic",
  "MV Boli",
  "Myanmar Text",
  "Nirmala UI",
  "Palatino Linotype",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Historic",
  "Segoe UI Emoji",
  "Segoe UI Symbol",
  "SimSun",
  "Sitka",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
  "Webdings",
  "Wingdings",
  "Yu Gothic",

  // ==================
  // macOS System Fonts
  // ==================
  "American Typewriter",
  "Andale Mono",
  "Apple Braille",
  "Apple Chancery",
  "Apple Color Emoji",
  "Apple SD Gothic Neo",
  "Apple Symbols",
  "AppleGothic",
  "AppleMyungjo",
  "Arial Hebrew",
  "Arial Unicode MS",
  "Avenir",
  "Avenir Next",
  "Avenir Next Condensed",
  "Baskerville",
  "Big Caslon",
  "Bodoni 72",
  "Bodoni 72 Oldstyle",
  "Bodoni 72 Smallcaps",
  "Bradley Hand",
  "Brush Script MT",
  "Chalkboard",
  "Chalkboard SE",
  "Chalkduster",
  "Charter",
  "Cochin",
  "Copperplate",
  "Courier",
  "Didot",
  "DIN Alternate",
  "DIN Condensed",
  "Diwan Misri",
  "Euphemia UCAS",
  "Futura",
  "Geneva",
  "Gill Sans",
  "Helvetica",
  "Helvetica Neue",
  "Herculanum",
  "Hoefler Text",
  "InaiMathi",
  "Iowan Old Style",
  "Klee",
  "Kohinoor Bangla",
  "Kohinoor Devanagari",
  "Kohinoor Telugu",
  "Lucida Grande",
  "Luminari",
  "Marker Felt",
  "Menlo",
  "Monaco",
  "Mshtakan",
  "Mukta Mahee",
  "New York",
  "Noteworthy",
  "Optima",
  "Osaka",
  "Palatino",
  "Papyrus",
  "Party LET",
  "Phosphate",
  "PingFang HK",
  "PingFang SC",
  "PingFang TC",
  "Rockwell",
  "San Francisco",
  "Savoye LET",
  "Seravek",
  "SignPainter",
  "Skia",
  "Snell Roundhand",
  "Sukhumvit Set",
  "Superclarendon",
  "Symbol",
  "Thonburi",
  "Times",
  "Trattatello",
  "Zapf Dingbats",
  "Zapfino",

  // ==================
  // Linux System Fonts
  // ==================
  "Bitstream Vera Sans",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "FreeMono",
  "FreeSans",
  "FreeSerif",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Serif",
  "Linux Libertine",
  "Nimbus Mono L",
  "Nimbus Roman No9 L",
  "Nimbus Sans L",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Light",
  "Ubuntu Mono",

  // ==================
  // Developer / Coding Fonts
  // ==================
  "Cascadia Code",
  "Cascadia Mono",
  "Fira Code",
  "Fira Mono",
  "Hack",
  "JetBrains Mono",
  "Source Code Pro",
  "Inconsolata",
  "Input Mono",
  "Operator Mono",
  "Dank Mono",
  "MonoLisa",

  // ==================
  // Adobe / Design Fonts
  // ==================
  "Acumin Pro",
  "Adobe Caslon Pro",
  "Adobe Garamond Pro",
  "Minion Pro",
  "Myriad Pro",
  "Source Sans Pro",
  "Source Serif Pro",
  "Trajan Pro",

  // ==================
  // Microsoft Office Fonts
  // ==================
  "Algerian",
  "Book Antiqua",
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Curlz MT",
  "Edwardian Script ITC",
  "Elephant",
  "Engravers MT",
  "Eras Bold ITC",
  "Estrangelo Edessa",
  "Felix Titling",
  "Footlight MT Light",
  "Freestyle Script",
  "French Script MT",
  "Gigi",
  "Gill Sans MT",
  "Gloucester MT Extra Condensed",
  "Goudy Old Style",
  "Goudy Stout",
  "Harrington",
  "High Tower Text",
  "Imprint MT Shadow",
  "Informal Roman",
  "Jokerman",
  "Juice ITC",
  "Kristen ITC",
  "Kunstler Script",
  "Lucida Bright",
  "Lucida Calligraphy",
  "Lucida Fax",
  "Lucida Handwriting",
  "Lucida Sans",
  "Lucida Sans Typewriter",
  "Magneto",
  "Maiandra GD",
  "Matura MT Script Capitals",
  "Mistral",
  "Modern No. 20",
  "Monotype Corsiva",
  "OCR A Extended",
  "Old English Text MT",
  "Onyx",
  "Palace Script MT",
  "Perpetua",
  "Playbill",
  "Poor Richard",
  "Ravie",
  "Rockwell Extra Bold",
  "Script MT Bold",
  "Showcard Gothic",
  "Snap ITC",
  "Stencil",
  "Tw Cen MT",
  "Viner Hand ITC",
  "Vivaldi",
  "Vladimir Script",
  "Wide Latin",
];