export const TOP_PRIORITY_TOOL_SLUGS = [
  "api-stress-estimator",
  "json-editor",
  "csv-converter",
  "csv-to-json",
  "text-case-converter",
  "word-character-counter",
  "url-encoder-decoder",
  "base64-to-text",
  "text-to-base64",
  "base64-to-image",
  "base64-to-pdf",
  "file-to-base64",
  "image-to-base64",
  "image-compressor",
  "image-resizer",
  "image-cropper",
  "pdf-merger",
  "pdf-split-tool",
  "pdf-to-base64",
  "pdf-to-image-converter",
  "svg-to-image",
  "qr-generator",
  "password-generator",
  "regex-tester",
  "jwt-decoder",
  "diff-checker",
  "markdown-preview",
  "markdown-html-converter",
  "html-to-markdown-converter",
  "color-contrast-checker",
  "gradient-generator",
  "barcode-generator",
  "uuid-generator",
  "unix-timestamp-converter",
  "unit-converter",
  "percentage-calculator",
  "gst-calculator",
  "loan-emi-calculator",
  "sip-calculator",
  "bmi-calculator",
];

export function normalizeToolCategory(category) {
  if (Array.isArray(category)) return category.filter(Boolean).join(", ");
  return category || "Uncategorized";
}
