export const deviceProfiles = {
  phone: {
    category: "mobile",
    baseDegradation: 0.45,
    heatSensitivity: 1.3,
    usageMultiplier: 1.0,
    lifespanMonths: 36,
    cycleLifespan: 500,        // typical charge cycles to 80% health
  },
  tablet: {
    category: "mobile",
    baseDegradation: 0.4,
    heatSensitivity: 1.25,
    usageMultiplier: 0.95,
    lifespanMonths: 42,
    cycleLifespan: 500,
  },
  laptop: {
    category: "laptop",
    baseDegradation: 0.35,
    heatSensitivity: 1.4,
    usageMultiplier: 0.9,
    lifespanMonths: 48,
    cycleLifespan: 800,
  },
  "ev-car": {
    category: "ev",
    baseDegradation: 0.18,
    heatSensitivity: 1.6,
    usageMultiplier: 1.4,
    lifespanMonths: 120,
    cycleLifespan: 1500,
  },
  "ev-scooter": {
    category: "ev",
    baseDegradation: 0.22,
    heatSensitivity: 1.5,
    usageMultiplier: 1.2,
    lifespanMonths: 72,
    cycleLifespan: 1000,
  },
  ups: {
    category: "misc",
    baseDegradation: 0.3,
    heatSensitivity: 1.25,
    usageMultiplier: 1.0,
    lifespanMonths: 48,
    cycleLifespan: 300,
  },
  powerbank: {
    category: "misc",
    baseDegradation: 0.5,
    heatSensitivity: 1.2,
    usageMultiplier: 0.8,
    lifespanMonths: 30,
    cycleLifespan: 300,
  },
  earbuds: {
    category: "misc",
    baseDegradation: 0.6,
    heatSensitivity: 1.1,
    usageMultiplier: 0.7,
    lifespanMonths: 24,
    cycleLifespan: 200,
  },
  inverter: {
    category: "misc",
    baseDegradation: 0.28,
    heatSensitivity: 1.3,
    usageMultiplier: 1.1,
    lifespanMonths: 60,
    cycleLifespan: 400,
  },
};